//Given a string. Write a method to return all its subsequences in an arraylist. A String is a subsequence of a given
// String that is generated by deleting some character of a given string without changing its order.
/*
   INPUT : abc
   OUTPUT : a,b,c,ab,bc,ac,abc, ,
 */
import java.util.Scanner;
import java.util.ArrayList;
public class Recursion33 {
    static ArrayList<String> getSSQ(String str){
        ArrayList<String> ans= new ArrayList<>();
        if(str.length()==0) {
            ans.add("");
            return ans;
        }
        char currChar = str.charAt(0);
        ArrayList<String> smallAns= getSSQ(str.substring(1));
        for(String ss: smallAns){
            ans.add(ss);
            ans.add(currChar+ss);
        }
        return ans;
    }
    public static void main(String[] args){
        Scanner sc= new Scanner(System.in);
        System.out.println("Enter the String");
        String str=sc.nextLine();
        ArrayList<String> al=getSSQ(str);
        System.out.println("Subsequences of string "+ str +" are:-");
        for(String ss: al){
            System.out.println(ss);
        }
    }
}
